export const surpriseMePrompts = [
    'A dragon riding a bicycle through a cityscape.',
    'A pineapple wearing sunglasses playing a guitar on the beach.',
    'A floating island made entirely of candy.',
    'A group of robots having a picnic in a flower meadow.',
    'A futuristic city with flying cars and neon-lit skyscrapers.',
    'A cat wearing a top hat and monocle, sipping tea at a tea party.',
    'An underwater scene with colorful coral reefs and exotic fish.',
    'A treehouse village nestled in a magical forest.',
    'A steampunk-inspired hot air balloon race.',
    'A library filled with books that come to life when opened.',
    'A surreal landscape where mountains are made of marshmallows.',
    'A group of animals having a dance party in a disco ballroom.',
    'A serene waterfall flowing through a serene bamboo forest.',
    'A castle floating in the clouds with a rainbow bridge leading to it.',
    'A spaceship exploring a galaxy filled with vibrant nebulas.',
    'A garden of giant flowers with whimsical creatures hiding among them.',
    'A city skyline at sunset, with colorful hot air balloons floating in the sky.',
    'A magical door hidden behind a waterfall, leading to a mystical realm.',
    'A snowy village inhabited by friendly yetis and talking snowmen.',
    'A roller coaster that twists and turns through a dense jungle.',
    'A field of sunflowers stretching as far as the eye can see.',
    'A group of fairies riding on the back of hummingbirds.',
    'A cityscape where buildings are shaped like musical instruments.',
    'A giant tree with treehouses built within its branches.',
    'A surreal desert landscape with floating islands and flying elephants.',
    'A whimsical carousel with mythical creatures as the ride\'s occupants.',
    'A vibrant underwater garden with glowing plants and sea creatures.',
    'A steampunk-inspired city powered by steam and clockwork mechanisms.',
    'A futuristic city where people travel on levitating hoverboards.',
    'A field of colorful mushrooms with magical properties.',
    'A secret garden hidden within an old abandoned castle.',
    'A bustling marketplace filled with fantastical creatures and exotic goods.',
    'A group of animals having a bonfire and telling stories under the stars.',
    'A bridge made entirely of rainbow-colored glass.',
    'A floating city in the sky with airships and floating islands.',
    'A tropical island paradise with palm trees and crystal-clear waters.',
    'A castle made of ice, shimmering in the moonlight.',
    'A whimsical village inhabited by friendly gnomes and fairies.',
    'A mystical forest with trees that have glowing bioluminescent leaves.',
    'A serene lake surrounded by majestic mountains and waterfalls.',
    'A group of friendly aliens playing soccer on an alien planet.',
    'A cityscape where buildings are made of candy and chocolate.',
    'A magical train traveling through a tunnel made of rainbow-colored glass.',
    'A floating waterfall that defies gravity, pouring water into the sky.',
    'A garden where flowers bloom in various shapes and colors.',
    'A castle perched on top of a floating rock in the sky.',
    'A mysterious cave filled with glowing crystals and ancient artifacts.',
    'A futuristic city with holographic displays and flying taxis.',
    'A group of animals having a costume party in the jungle.',
    'A whimsical circus with acrobats, jugglers, and performing animals.',
];
